### ISSUE TITLE
Incompatibility with Floki: 0.36.3

### ISSUE THREAD

**Issue by ulissesalmeida** [danschultzer/premailex#91]
```
     ** (MatchError) no match of right hand side value: []
     stacktrace:
       (floki 0.36.3) lib/floki/finder.ex:56: Floki.Finder.find/2
       (premailex 0.3.19) lib/premailex/html_inline_styles.ex:131: Premailex.HTMLInlineStyles.add_rule_set_to_html/2
       (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
       (premailex 0.3.19) lib/premailex/html_inline_styles.ex:84: Premailex.HTMLInlineStyles.apply_styles/2
       (premailex 0.3.19) lib/premailex/html_inline_styles.ex:52: Premailex.HTMLInlineStyles.process/3
```

Changelog of Floki:

```
[0.36.3] - 2024-10-21
This release contains some performance improvements, thanks to [@​ypconstante](https://github.com/ypconstante).

Fixed
Stop Floki.get_by_id/2 traversal on first match. Thanks [@​ypconstante](https://github.com/ypconstante).

Remove extra whitespaces from nodes without attributes on Floki.raw_html/1. Thank you [@​ypconstante](https://github.com/ypconstante).

Fix Floki.raw_html/1 typespecs. Thanks [@​davydog187](https://github.com/davydog187).
```

We're using premailex: 0.3.19

Let me know if you need any more info, I omitted the company code stack trace.

**Comment by danschultzer** [comment]
Thanks, can you share an example with what CSS/HTML causes this? I can't reproduce this.

**Comment by angelcarballo** [comment]
hi @danschultzer . This is a sample that fails with premailex: 0.3.19 and floki 0.36.3 (also with floki 0.37.0) 

<details>
  <summary>Sample</summary>

```
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="x-apple-disable-message-reformatting" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style type="text/css">
      @font-face {
        font-weight: 400; /* Normal */
        font-family: "GT America";
        font-style: normal;
        src: url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Regular.eot");
        src: url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Regular.eot?#iefix")
            format("embedded-opentype"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Regular.woff2")
            format("woff2"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Regular.woff")
            format("woff"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Regular.ttf")
            format("truetype");
      }

      @font-face {
        font-weight: 500; /* Medium */
        font-family: "GT America";
        font-style: normal;
        src: url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Medium.eot");
        src: url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Medium.eot?#iefix")
            format("embedded-opentype"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Medium.woff2")
            format("woff2"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Medium.woff")
            format("woff"),
          url("https://assets.duffel.com/fonts/gt-america-standard/GT-America-Standard-Medium.ttf")
            format("truetype");
      }

      body {
        margin: 0 !important;
        padding: 0 !important;
        font-size: 16px !important;
        line-height: 150% !important;
        letter-spacing: 0em !important;
        background-color: #F6F5F9 !important; /* Grey-100 */
        color: #1a1c24 !important;
        font-family: "GT America", -apple-system, BlinkMacSystemFont, Segoe UI,
          Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji !important;
        -webkit-font-smoothing: antialiased;
      }

      img {
        border: 0 none !important;
        line-height: 100% !important;
        outline: none !important;
        text-decoration: none !important;
      }

      a img {
        border: 0 none !important;
      }

      table,
      td {
        border-collapse: collapse !important;
      }

      .tc {
        text-align: center !important;
      }

      .body-table {
        height: 100% !important;
        margin: 0 !important;
        padding: 0 !important;
        width: 100% !important;
        background-color: #F6F5F9 !important; /* Grey-100 */
      }

      .email {
        padding: 36px 12px !important;
      }

      .email__section {
        padding: 12px !important;
      }

      .email__content {
        padding-top: 24px !important;
        padding-bottom: 24px !important;
      }

      .email__content__body {
        margin-left: auto !important;
        margin-right: auto !important;
        background: #fff !important;
        max-width: 580px !important;
        width: 100% !important;
        border-radius: 4px !important;
      }

      .email__content__body__cell {
        padding: 48px !important;
      }

      .email__content__body__cell > *,
      .email__section > * {
        margin-bottom: 0 !important;
      }

      .email__content__body__cell > *:first-child,
      .email__section > *:first-child {
        margin-top: 0 !important;
      }

      .email__footer {
        color: #8187a6 !important;
      }

      h1, h2, h3, h4 {
        font-family: "GT America", -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji !important;
      }

      h1 {
        color: #100024 !important;
        font-weight: 400 !important;
        font-size: 40px !important;
        line-height: 120% !important;
        letter-spacing: -1px !important;
      }

      h2 {
        color: #100024 !important;
        font-weight: 500 !important;
        font-size: 30px !important;
        line-height: 120% !important;
        letter-spacing: -0.01em !important;
      }

      h4 {
        font-weight: 500 !important;
        font-size: 20px !important;
        line-height: 130% !important;
        letter-spacing: 0em !important;
        color: #100024 !important; /* Purple-900 */
      }

      a {
        cursor: pointer !important;
        color: #100024 !important; /* Purple-900 */
        text-decoration: underline !important;
      }

      a:hover {
        color: #413463 !important; /* Purple-800 */
      }

      a:active {
        color: #ABABB4 !important; /* Grey-400 */
      }

      h1 + p, h2 + p, h3 + p, h4 + p,  {
        margin-top: 24px !important;
      }

      p {
        color: #4b4b55;
        font-size: 16px !important;
        line-height: 150% !important;
        letter-spacing: 0em !important;
        margin: 0px !important;
      }

      p + p {
        margin-top: 16px !important;
      }

      p.text-small {
        font-size: 14px !important;
        line-height: 150% !important;
        letter-spacing: 0em !important;
      }

      .purple-800 {
        color: #413463 !important;
      }

      .purple-900 {
        color: #100024 !important;
      }

      .grey-400 {
        color: #ABABB4 !important;
      }

      .grey-500 {
        color: #86868e !important;
      }

      a.cta-button {
        cursor: pointer !important;
        color: white !important ;
        width: fit-content !important;
        background-color: #100024 !important; /* Purple-900 */
        display: block !important;
        padding: 8px 32px !important;
        font-size: 16px !important;
        line-height: 150% !important;
        letter-spacing: 0em !important;
        color: #ffffff !important;
        text-decoration: none !important;
        border: none !important;
        border-radius: 100px !important;
        text-align: center !important;
        box-sizing: border-box !important;
        margin-top: 48px;
      }

      a:not(.cta-button):not(.get-to-know-cards):hover {
        text-decoration: underline !important;
      }

      a.cta-button:hover {
        background: #413463 !important; /* Purple-800 */
        color: #ffffff !important;
      }

      a.cta-button:active {
        background: #ABABB4 !important; /* Grey-400 */
        color: #ffffff !important;
      }

      a.get-to-know-cards:hover h3 {
        text-decoration: underline !important;
      }

      .anchor-arrow-icon {
        font-feature-settings: 'kern' 1, 'ss03' 1;
      }
    </style>
    <!--[if mso]>
      <style type="text/css">
        .f-fallback {
          font-family: Arial, sans-serif;
        }
      </style>
    <![endif]-->
  </head>
  <body>
    <table
      class="body-table"
      width="100%"
      cellpadding="0"
      cellspacing="0"
      role="presentation"
    >
      <tbody>
        <tr>
          <td class="email">
            <table
              width="100%"
              cellpadding="0"
              cellspacing="0"
              role="presentation"
            >
              <tbody>
                <tr>
                  <td class="tc email__section email__header">
                  <a href='https://duffel.com'>
                    <img
                      height="26px"
                      alt="Duffel logo lockup"
                      src="https://storage.googleapis.com/duffel-assets/img/emails/logo.png"
                    />
                  </a>
                  </td>
                </tr>
                <tr>
                  <td class="email__section email__content">
                    <table
                      class="email__content__body"
                      cellpadding="0"
                      cellspacing="0"
                    >
                      <tr>
                        <td class="email__content__body__cell f-fallback">
                          <table>
                            <tbody>
                              <tr>
                                <td>
<img
  alt="Warning icon"
  height="64px"
  width="64px"
  src="https://storage.googleapis.com/duffel-assets/img/emails/refresh/Complex-Icons-Low-Balance.png"
/>
<h2 style="margin-top: 48px;">You’re running low!</h2>
<p>
  It looks like it might be time to make a pit stop and refuel your Alternative Airlines Duffel balance.
</p>
<p>
  Your balance is currently below £1000 - we’d recommend
  topping up so you can continue to book flights or accommodation with Duffel.
</p>
<p>
  You'll need to have enough money in your balance or you won't be able to create or change bookings.
</p>
<a class="cta-button" href="https://localhost:3000/alt_air/live/wallet">Top up</a>
<tr style="height: 48px !important;"></tr>
<tr style="height: 2px !important;">
  <td style="background: #e2e2e8;"></td>
</tr>
<tr style="height: 48px !important;"></tr>
<tr>
  <td>
    <p
      class="grey-500"
      style="margin-top: 0px !important;"
    >
      <span class="purple-900">
        Need help with your account?
      </span>
      Head to our
      <a href="https://help.duffel.com/">
        Help Centre
      </a>.
      Alternatively, don’t hesitate to reach out to our team at
      <a href="mailto:help@duffel.com">
        help@duffel.com
      </a>.
    </p>
  </td>
</tr>

                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td class="tc email__section email__footer">
                    <p class="text-small grey-500">
Duffel Technology Ltd -
3rd Floor, 100 Clifton Street, London, EC2A 4TP. <br />
                    </p>
                    <p class="text-small grey-500">
                      This email was sent to you as a registered member of
                      duffel.com to update you
                      <br />
                      about important information regarding your account. For
                      any questions or
                      <br />
                      concerns and support
                      <a href="mailto:help@duffel.com">click here</a>.
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
```
</details>

**Comment by danschultzer** [comment]
Thanks, it's because of this empty selector:

```css
h1 + p, h2 + p, h3 + p, h4 + p,  {
  margin-top: 24px !important;
}
```

I'll add logic to filter out empty selectors.
